#!/usr/bin/env bash

set -e

run-lambda-test()
{
  handler=$1
  event=$2
  echo 'Run a lambda-test'
  docker run -v $(PWD):/code lambda-local -f $handler -t 5 entrypoint.py $event
}

run-lambda-test proxy_handler fixtures/event1.json
